# Напредно програмирање : Аудиториски вежби 3
М-р Томче Делев <tdelev@finki.ukim.mk>
{docdate}
:stem: latexmath
:toc-title: Содржина
:figure-caption: Слика
:numbered:
:latexmath:
:source_dir: ../../examples/src/main/java/mk/ukim/finki/np/av3

== Читање од SI

=== Задача

Да се напише програма едноставен калкулатор. Калкулаторот чува еден број од тип
`double` со име резултат и неговата почетна вредност е `0.0`. Во циклус му
се дозволува на корисникот да додаде, одземе, помножи или подели со втор број.
Резултатот од овие операции е новата вредност на резултатот. Пресметката
завршува кога корисникот ќе внесе R за `result` (како мала или голема буква).
Корисникот може да направи уште една пресметка од почеток или да ја заврши
програмата `(Y/N)`.
Ако корисникот внесе различен знак за оператор од `+`, `-`, `*` или `/`,
тогаш се фрла исклучок `UnknownOperatorException` и се чека повторно на внес.

.Пример форматот на влезните податоци:

[source,bash]
----
Calculator is on.
result = 0.0
+5
result + 5.0 = 5.0
new result = 5.0
* 2.2
result * 2.2 = 11.0
updated result = 11.0
% 10
% is an unknown operation.
Reenter, your last line:
* 0.1
result * 0.1 = 1.1
updated result = 1.1
r
Final result = 1.1
Again? (y/n)
yes
result = 0.0
+10
result + 10.0 = 10.0
new result = 10.0
/2
result / 2.0 = 5.0
updated result = 5.0
r
Final result = 5.0
Again? (y/n)
N
End of Program
----

.Решение 1
[source,java]
----
include::{source_dir}/Calculator.java[]
----

.Решение 1 (Тест програма)
[source,java]
----
include::{source_dir}/CalculatorTest.java[]
----

== Текстуални датотеки

=== Задача

Да се напише програма која го прикажува бројот на знаци, бројот на зборови и
бројот на редови во датотеките чии што имиња се задаваат како аргументи на
командна линија.

.Решение 2
[source,java]
----
include::{source_dir}/WordCount.java[]
----

=== Задача

Во секој ред од една датотека се запишани име (`String`) и возраст
(`int`). Да се напише програма која ќе го отпечати името и возраста на
највозрасното лице.

[source]
----
Кристијан 25
Дритон 39
Ристе 17
Лусијана 28
Бобан 7
Оливера 71
Ана 14
Димитар 56
Диме 11
Билјана 12
----

.Решение 3
[source,java]
----
include::{source_dir}/FindOldest.java[]
----


=== Задача

Да се напише програма која пресметува оценки за одреден курс. Во програмата прво
се вчитува името на датотеката која ги содржи информациите за резултатите од
испититите. Секој ред од датотеката е во следниот формат:

`LastName:FirstName:Exam1:Exam2:Exam3`

Испитите се вреднуваат тежински и тоа 25% за првиот, 30% за вториот и 45% за
третиот испит. Врз основа на ова, конечната оценка се добива според следната
скала:

- 90 - 100 A
- 80 - 90 B
- 70 - 80 C
- 60 - 70 D
- 0 - 60 F

Вашата програма треба да отпечати на стандардниот излез листа од студенти со
оценката во следниот формат:

`LastName FirstName LetterGrade`

Исто така во датотека чие што име се внесува од стандарден влез се запишуваат
резултатите во следнио формат:

`LastName FirstName Exam1 Exam2 Exam3 TotalPoints LetterGrade`

Откако ќе се запише оваа содржина во датотека, се печати на стандарден излез
дистрибуцијата на оценките.

Пример ако содржината на датотеката е:

[source]
----
Doe:John:100:100:100
Pantz:Smartee:80:90:80
----

Излезот е:
----
Doe John A
Pantz Smartee B
----

Излезот во датотеката ќе биде:
----
Doe John 100 100 100 100 A
Pantz Smartee 80 90 80 83 B
A 1
B 1
C 0
D 0
F 0
----

.Решение 4
[source,java]
----
include::{source_dir}/CalculateGrades.java[]
----

== Бинарни датотеки

=== Задача

Да се напише програма која запишува n случајни броеви во бинарна датотека, потоа
ги вчитува и пресметува просек.


.Решение 1
[source,java]
----
include::{source_dir}/BinaryNumbers.java[]
----

=== Задача

Да се напише класа за резултат (`Score`) од некоја видео игра. Секој
резултат се состои од името и бројот на поени. Да се напише нова класа
(`Scoreboard`) која ќе ги чува најдобрите N резултати. Оваа класа треба да има
можност за додавање нов резултат и прикажување на тековните резултати.

NOTE: За дома