# Напредно програмирање
Аудиториски вежби 2
v1.0, 23 Септември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../examples/src/main/java/mk/ukim/finki/np/av2

## Задача

Да се напише метод кој враќа точно ако `String str1` е префикс на `String str2`.
Не е дозволено користење на готови методи за пребарување, единствено дозволено е
користење на `charAt`.

.Решение 1 (`isPrefix`)
[source,java]
----
include::{source_dir}/Examples2.java[tag=prefix]
----

## Задача

Да се имплементираат следните методи кои примаат дво-димензионални низи од
double и враќаат како резултат сума и просек.

[source,java]
----
public static double sum(double[][] a)
public static double average(double[][] a)
----

.Решение 2 (`sum`)
[source,java]
----
include::{source_dir}/Examples2.java[tag=sum,indent=0]
----

.Решение 2 (`average`)
[source,java]
----
include::{source_dir}/Examples2.java[tag=average,indent=0]
----


## Задача

Катанец со комбинации `Combination Lock` ги има следните својства:

- комбинацијата (секвенца од 3 цифри) е скриена
- катанецот може да се отвори само ако се внесе точната комбинација
- комбинацијата може да се промени само ако се знае претходната
  комбинација.

Да се дизајнира класа со јавни методи `open` и `changeCombo` и
приватни податоци кои ја чуваат комбинацијата. Комбинацијата се
поставува преку конструкторот.

.Решение 3 (`CombinationLock.java`)
[source,java]
----
include::{source_dir}/CombinationLock.java[]
----

## Задача

Имплементирајте едноставна класа за датум `Date`.
Вашата класа треба да може:

- да ги репрезентира сите датуми од 1 Јануари 1800 до 31 Декември 2500
- одзема два датуми
- зголеми датум за даден број денови
- да споредува два датуми со помош на `equals` и `compareTo`.

Датумот внатрешно ќе се репрезентира како број на денови од почетното време, кое
во овој случај е почетокот на 1800. Со ова сите методи освен методот
`toString` се поедноставуваат. Да се запази правилото за престапни години
(престапна година е секоја година која е делива со 4 и не е делива со 100 освен
ако е делива со 400). Конструкторот треба да ја провери валидноста на датумот, а
исто така и методот `toString`. Датумот може да стане неточен ако
зголемувањето или намалувањто придонсе да излезе надвор од опсегот.

Потешкиот дел од задачата е конверзијата од интерната репрезентација во
надворешна репрезентација на датум. Еден предлог алгоритам е следниот. Се
иницијализираат две низи во статички членови. Првата низа е денови до први во
месецот (daysTillFirstOfMonth) во не престапна година. Оваа низа содржи 0, 31,
59, 90, итн. Во втората низа, денови од почетокот на првата година
(daysTillJan1). Така оваа низа ќе содржи 0, 365, 730, 1095, 1460, 1826, итн. Со
помош на овие низи ќе ја правиме конверзијата на различни репрезентации на
датум.

.Решение 4 (`Date.java`)
[source,java]
----
include::{source_dir}/Date.java[]
----

## Задача

`PlayingCard` (карта) е класа со која се репрезентира карта во игри со
карти како покер и блек џек и во не се чува информација за бојата (херц, каро, пик, треф) и
рангот (вредност од 2 до 10 или џандар, кралица, поп или ас). `Deck`
(шпил од карти) е класа која репрезентира комплет од 52 карти. Додека
`MultipleDeck` (повеќе шпилови) е класа која репрезентира повеќе шпилови
со карти (точниот број се задава во конструкторот). Да се имплментираат 3 класи
`PlayingCard`, `Deck`, и `MultipleDeck`, со стандардна
функционалност за карта, за шпил и повеќе шпилови да се имплментираат методи за
мешање `shuffle`, делење на карта  `dealCard` и проверка дали има
останато карти.

.Решение 4 (`PlayingCard.java`)
[source,java]
----
include::{source_dir}/PlayingCard.java[]
----

.Решение 4 (`Deck.java`)
[source,java]
----
include::{source_dir}/Deck.java[]
----

.Решение 4 (`MultipleDeck.java`)
[source,java]
----
include::{source_dir}/MultipleDeck.java[]
----

## Задача

Комплексен број се состои од реален дел и имагинарен дел. Да се импалементира
класа `BigComplex`, во која реалниот и имагинарниот дел ќе се чуваат во
објекти од класата `BigDecimals`.


.Решение 5 (`BigComplex.java`)
[source,java]
----
include::{source_dir}/BigComplex.java[]
----

.За дома
NOTE: Имплементирајте ги останатите методи за
одземање `subtract`, множење `multiply` и делење `divide`.

## Задача

Дадени се следниве пет класи:

. `Bank`
. `Account`
. `NonInterestCheckingAccount`
. `InterestCheckingAccount`
. `PlatinumCheckingAccount`

како и интефејс наречен `InterestBearingAccount` кои се однесуваат на следниот начин:

* Во `Bank` чува листа од сите видови сметки, вклучувајќи сметки
за штедење и за трошење, некои од нив подложни на камата, а некои не.
Во `Bank` постои метод `totalAssets` кој ја враќа сумата на состојбата на сите сметки.
Исто така содржи метод `addInterest` кој го повикува методот `addInterest`
на сите сметки кои се подложни на камата.
* `Account` е апстрактна класа. Во секој сметка се чуваат името на
сопственикот на сметката, бројот на сметката (секвенцијален број доделен
автоматски), моменталната состојба.
Во класата се имплементираат конструктор за иницијализација на
податочните членови, методи за пристап до моменталната
 состојба, како и за додавање и одземање од моменталната состојба.
* `InterestBearingAccount` интерфејсот декларрира единствен метод
`addInterest` (без параметри и не враќа ништо - `void`) кој ја зголемува
состојбата со соодветната камата за овој вид на сметка.
* `InterestCheckingAccount` е сметка `Account` која е исто
така `InterestBearingAccount`. Повикување `addInterest` ја
зголемува состојбата за 3%.
* `PlatinumCheckingAccount` е `InterestCheckingAccount`.
Повикување `addInterest` ја зголемува состојбата двојно од каматата за
`InterestCheckingAccount` (колку и да е таа).
* `NonInterestCheckingAccount` е сметка `Account` но не е
`InterestBearingAccount`. Нема дополнителни функционалности надвор од
основните од класата `Account`.

За оваа задача, потребно е да се имплментира функционалност дадена
во претходниот текст:
  
  . Пет од шест класи од споменатите формираат хиерархија. За овие класи да
  се нацрта оваа хиерархија.
  . Да се имплементира `Account`.
  . Да се имплементира `NonInterestCheckingAccount`.
  . Да се напише `InterestBearingAccount` интерфејсот.
  . Да се имплементира `Bank`.
  . Да се имплементира `InterestCheckingAccount`.
  . Да се имплементира `PlatinumCheckingAccount`.


.Решение 6 (`Account.java`)
[source,java]
----
include::{source_dir}/bank/Account.java[]
----

.Решение 6 (`NonInterestCheckingAccount.java`)
[source,java]
----
include::{source_dir}/bank/NonInterestCheckingAccount.java[]
----

.Решение 6 (`InterestBearingAccount.java`)
[source,java]
----
include::{source_dir}/bank/InterestBearingAccount.java[]
----

.Решение 6 (`Bank.java`)
[source,java]
----
include::{source_dir}/bank/Bank.java[]
----

.Решение 6 (`InterestCheckingAccount.java`)
[source,java]
----
include::{source_dir}/bank/InterestCheckingAccount.java[]
----

.Решение 6 (`PlatinumCheckingAccount.java`)
[source,java]
----
include::{source_dir}/bank/PlatinumCheckingAccount.java[]
----

include::parts/footer.adoc[]

link:{sources_zip}/np_av2_src.zip[Source Code ZIP]
