# Напредно програмирање
Аудиториски вежби 2
v1.0, 23 Септември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../examples/src/main/java/mk/ukim/finki/np/av2

## String prefix

Да се напише метод кој враќа точно ако `String str1` е префикс на `String str2`.
Не е дозволено користење на готови методи за пребарување, единствено дозволено е користење на `charAt`.

.Решение (`isPrefix`)
[source,java]
----
include::{source_dir}/Examples2.java[tag=prefix]
----

.Решение со Java 8 Streams (`isPrefixStream`)
[source,java]
----
include::{source_dir}/Examples2.java[tag=prefix_stream]
----

## Матрица (сума и просек)

Да се имплементираат следните методи кои примаат дво-димензионални низи од `double` и враќаат како резултат сума и просек.

[source,java]
----
public static double sum(double[][] a)
public static double average(double[][] a)
----

.Решение (`sum`)
[source,java]
----
include::{source_dir}/Examples2.java[tag=sum,indent=0]
----

.Решение со Java 8 Streams (`sumStream`)
[source,java]
----
include::{source_dir}/Examples2.java[tag=sum_stream,indent=0]
----

.Решение 2 (`average`)
[source,java]
----
include::{source_dir}/Examples2.java[tag=average,indent=0]
----


## Катанец (CombinationLock)

Катанец со комбинации `Combination Lock` ги има следните својства:

- комбинацијата (секвенца од 3 цифри) е скриена
- катанецот може да се отвори само ако се внесе точната комбинација
- комбинацијата може да се промени само ако се знае претходната комбинација.

Да се дизајнира класа со јавни методи `open` и `changeCombo` и приватни податоци кои ја чуваат комбинацијата.
Комбинацијата се поставува преку конструкторот.

.Решение (`CombinationLock.java`)
[source,java]
----
include::{source_dir}/CombinationLock.java[]
----

## BigComplex

Комплексен број се состои од реален дел и имагинарен дел.
Да се импалементира класа `BigComplex`, во која реалниот и имагинарниот дел ќе се чуваат во објекти од класата `BigDecimals`.

.Решение (`BigComplex.java`)
[source,java]
----
include::{source_dir}/BigComplex.java[]
----

.За дома
NOTE: Имплементирајте ги останатите методи за одземање `subtract`, множење `multiply` и делење `divide`.

include::parts/footer.adoc[]

link:{sources_zip}/np_av2_src.zip[Source Code ZIP]
