# Напредно програмирање
Аудиториски вежби 5
v1.0, 20 Септември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../examples/src/main/java/mk/ukim/finki/np/av5

== ArrayList

`ArrayList` е класа од стандарадните библиотеки во Java која го имплементира интерфејсот `List`.
За разлика од низите, кои имаат фиксна должина откако ќе се креираат, `ArrayList` е објект коj може да се проширува додека програмата се извршува.
Генерално, `ArrayList` jа има истата улога како и низите, со тоа што може да jа менува својата должина за време на извршувањето на програмата.
Имплементирана е со помош на низа како приватна класна променлива.

=== Зошто секогаш да не користиме ArrayList наместо низи?

. `ArrayList` е по неефикасна од низа
. Не подржува нотациjа на големи загради `[]`
. Основниот тип на ArrayList мора да биде класа (или друг тип референца): не може да биде примитивен тип `int`, `float`, `double`,...

=== Користење на `ArrayList`

* За да се користи ArrayList, треба да се вклучи од пакетот `java.util.ArrayList`
* Се креира и именува на ист начин како и објект од било која класа, освен што мора да се специфицира најзиниот тип на следниов начин:

[source,java]
----
ArrayList<BaseType> list = new ArrayList<>();
----

* Почетниот капацитет може да се проследи како аргумент на конструкторот
* Следниот код креира `ArrayList` коj чува референци од тип `String` и има почетен капацитет од 20 членови

[source,java]
----
ArrayList<String> strings = new ArrayList<>(20);
----

NOTE: Специфицирање на почетниот капацитет не jа ограничува големината до која `ArrayList` може да расте

=== Најчесто користени методи

* `add` се користи за дадовање на елемент
* Постои и преоптоварена верзија со два аргументи коj овозможува да се додаде елемент на одредена позиција зададена преку индекс
* Методот `size` се користи да се добие бројот на елементи

[source,java]
----
int howMany = list.size();
----

* Методот `set` се користи за менување на постоечки елемент
* Методот get се користи за пристапување до одреден постоечки елемент

И двата методи го примаат за аргумент индексот (0 базиран) на елементот коj сакаме да го пристапиме.

[source,java]
----
list.set(index, "something else");
String thing = list.get(index);
----

== Текстуални датотеки

=== Word Count

Да се напише програма која го прикажува бројот на знаци, бројот на зборови и бројот на редови во датотеките чии што имиња се задаваат како аргументи на командна линија.

.Решение 2
[source,java]
----
include::{source_dir}/WordCount.java[]
----

=== Oldest Person

Во секој ред од една датотека се запишани име (`String`) и возраст (`int`).
Да се напише програма која ќе го отпечати името и возраста на највозрасното лице.

[source]
----
Кристијан 25
Дритон 39
Ристе 17
Лусијана 28
Бобан 7
Оливера 71
Ана 14
Димитар 56
Диме 11
Билјана 12
----

.Решение 3
[source,java]
----
include::{source_dir}/FindOldest.java[]
----


=== Оценки за курс

Да се напише програма која пресметува оценки за одреден курс.
Во програмата прво се вчитува името на датотеката која ги содржи информациите за резултатите од испититите.
Секој ред од датотеката е во следниот формат:

`LastName:FirstName:Exam1:Exam2:Exam3`

Испитите се вреднуваат тежински и тоа 25% за првиот, 30% за вториот и 45% за третиот испит.
Врз основа на ова, конечната оценка се добива според следната скала:

- A [90 - 100)
- B [80 - 90)
- C [70 - 80)
- D [60 - 70)
- F [0 - 60)

Вашата програма треба да отпечати на стандардниот излез листа од студенти подредени според оценката во опаѓачки редослед, во следниот формат:

`LastName FirstName LetterGrade`

Исто така во датотека чие што име се внесува од стандарден влез се запишуваат резултатите во следниот формат:

`LastName FirstName Exam1 Exam2 Exam3 TotalPoints LetterGrade`

Откако ќе се запише оваа содржина во датотека, се печати на стандарден излез дистрибуцијата на оценките.

Пример ако содржината на датотеката е:

[source]
----
Doe:John:100:100:100
Pantz:Smartee:80:90:80
----

Излезот е:
----
Doe John A
Pantz Smartee B
----

Излезот во датотеката ќе биде:
----
Doe John 100 100 100 100 A
Pantz Smartee 80 90 80 83 B
A 1
B 1
C 0
D 0
F 0
----

.Решение (`Student.java`)
[source,java]
----
include::{source_dir}/Student.java[]
----

.Решение (`CalculateGrades.java`)
[source,java]
----
include::{source_dir}/CalculateGrades.java[]
----

.Решение со Java 8 Streams (`CalculateGradesImproved.java`)
[source,java]
----
include::{source_dir}/CalculateGradesImproved.java[]
----

=== Најдолг палиндром

Во датотеката `words.txt` има 99,171 зборови од Англискиот јазик.
Да се напише програма која ќе го пронајде најдолгиот збор палиндром.

.Решение (`LongestPalindrome.java`)
[source,java]
----
include::{source_dir}/LongestPalindrome.java[]
----

== Бинарни датотеки

=== Просек на случајни броеви

Да се напише програма која запишува `n` случајни цели броеви во бинарна датотека, потоа ги вчитува и го пресметува нивниот просек.

.Решение 1
[source,java]
----
include::{source_dir}/BinaryNumbers.java[]
----

=== Листа со резултати

Да се напише класа за резултат (`Score`) од некоја видео игра.
Секој резултат се состои од името и бројот на поени.
Да се напише нова класа (`Scoreboard`) која ќе ги чува најдобрите N резултати.
Оваа класа треба да има можност за додавање нов резултат и прикажување на тековните резултати.

NOTE: За дома

include::parts/footer.adoc[]

link:{sources_zip}/np_av5_src.zip[Source Code ZIP]