# Напредно програмирање
Аудиториски вежби 2
v1.0, 23 Септември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../examples/src/main/java/mk/ukim/finki/np/av1

## Задача

Да се напише програма која ќе ги најде сите парови позитивни цели броеви (a, b)
такви што a < b < 1000 и stem:[\frac{(a^2 + b^2 + 1)}{a * b}] е цел број.

.Решение 1
[source,java]
----
include::{source_dir}/Ex1.java[]
----

## Задача

Да се напише метод кој ќе прима еден цел број и ќе ја печати неговата
репрезентација како Римски број. Пример. ако ако се повика со парамететар 1998,
излезот треба да биде MCMXCVIII.

NOTE: За дома

## Задача

Ваша задача е да печатите броеви во средни загради, форматирани на следниот
начин: [1][2][3], итн. Напишете метод кој прима два параметри: `howMany` и
`lineLength` и ги печати броевите од `1` до `howMany` во претходно опишаниот формат,
со што не смее да се печатат повеќе знаци во една линија од `lineLength`. Не треба
да се започне со отворена заграда `[` ако не може да се затвори во истата линија
со соодветна `]`.

NOTE: За дома

include::parts/footer.adoc[]

link:{sources_zip}/np_av1_src.zip[Source Code ZIP]
