# Напредно програмирање
Аудиториски вежби 3
v1.0, 23 Септември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../examples/src/main/java/mk/ukim/finki/np/av3

## Датум

Имплементирајте едноставна класа за датум `Date`.
Класата треба да овозможува:

- репрезентација на сите датуми од 1 Јануари 1800 до 31 Декември 2500
- одземање два датуми
- зголемување датум за даден број денови
- да споредува два датуми со помош на `equals` и `compareTo`.

Датумот внатрешно ќе се репрезентира како број на денови од почетното време, кое во овој случај е почетокот на 1800.
Со ова сите методи освен методот `toString` се поедноставуваат.
Да се запази правилото за престапни години (престапна година е секоја година која е делива со 4 и не е делива со 100 освен ако е делива со 400).
Конструкторот треба да ја провери валидноста на датумот, а исто така и методот `toString`.
Датумот може да стане неточен ако зголемувањето или намалувањто придонсе да излезе надвор од опсегот.

Потешкиот дел од задачата е конверзијата од интерната репрезентација во надворешна репрезентација на датум.
Еден предлог алгоритам е следниот.
Се иницијализираат две низи во статички членови.
Првата низа е денови до први во месецот (daysTillFirstOfMonth) во не престапна година.
Оваа низа содржи 0, 31, 59, 90, итн.
Во втората низа, денови од почетокот на првата година (daysTillJan1) ќе содржи 0, 365, 730, 1095, 1460, 1826, итн.
Со помош на овие низи ќе ја правиме конверзијата на различни репрезентации на датум.

.Решение (`Date.java`)
[source,java]
----
include::{source_dir}/Date.java[]
----

## Карти (PlayingCard)

`PlayingCard` (карта) е класа со која се репрезентира карта во игри со карти како покер и блек џек.
Во неа се чува информација за бојата (херц, каро, пик, треф) и рангот (вредност од 2 до 10 или џандар, кралица, поп или ас).
`Deck` (шпил од карти) е класа која репрезентира комплет од 52 карти.
Додека `MultipleDeck` (повеќе шпилови) е класа која репрезентира повеќе шпилови со карти (точниот број се задава во конструкторот).
Да се имплментираат 3 класи `PlayingCard`, `Deck`, и `MultipleDeck`, со стандардна функционалност за карта, за шпил и повеќе шпилови.
Да се имплментираат методи за мешање `shuffle`, делење на карта  `dealCard` и проверка дали има останато карти.

.Решение (`PlayingCard.java`)
[source,java]
----
include::{source_dir}/PlayingCard.java[]
----

.Решение (`Deck.java`)
[source,java]
----
include::{source_dir}/Deck.java[]
----

.Решение (`MultipleDeck.java`)
[source,java]
----
include::{source_dir}/MultipleDeck.java[]
----

include::parts/footer.adoc[]

link:{sources_zip}/np_av2_src.zip[Source Code ZIP]
