# Напредно програмирање
Аудиториски вежби 6
v1.0, 20 Септември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../examples/src/main/java/mk/ukim/finki/np/av6

== Генеричко програмирање

=== Кутија

Да се напише генеричка класа кој симулира исцртување на случаен предмет од некоја кутија.
Оваа класа треба да се користи за случајно исцртување.
На пример, класата може да содржи листа со имиња и избира едно случајно име, или пак листа со броеви за лотарија и избира случајно број.
Креирајте метод `add` за додавање објект од соодветниот тип и метод `isEmpty` кој проверува дали кутијата е празна.
На крај, имплементирајте метод `drawItem` кој случајно избира објект од кутијата и го враќа како резултат.
Ако се обидеме да цртаме со празна кутија се враќа `null`.

Да се напише main метод кој ја тестира класата.


.Решение (`Box.java`)
[source,java]
----
include::{source_dir}/Box.java[]
----

=== Priority Queue (Ред на чекање со приоритет)

Да се имплементира класа за податочна структура `PriorityQueue` со помош на `ArrayList`.
`PriorityQueue` е податочна структура во која секој елемент е придружен заедно со неговиот приоритет (цел број).
Приоритет да се дефинира така што оние елементи со најголема вредност имаат повисок приоритет.
Класата треба да ги имплементира следните методи:

* `add(item, priority)` - додава нов елемент со асоциран приоритет
* `remove()` - го враќа елементот со најголем приоритет и го брише од редот.
Ако редот е празен се враќа `null`.

Пример за priority queue со стрингови:

[source,java]
----
q.add("X", 10);
q.add("Y", 1);
q.add("Z", 3);
System.out.println(q.remove()); // Returns X
System.out.println(q.remove()); // Returns Z
System.out.println(q.remove()); // Returns Y
----

Тестирајте го редот со податоци со приоритет во различен редослед (пр., растечки, опаѓачки, мешан).
Редот може да се имплементира со линеарно пребарување низ `ArrayList`.

.Решение (`PriorityQueue.java`)
[source,java]
----
include::{source_dir}/PriorityQueue.java[]
----

=== Стандардна девијација (MyMathClass)

Да се напише класа `MyMathClass`, во која ќе се имплементира статички метод `standardDeviation`.
Методот како аргумент прима `ArrayList` од тип `Т`, каде што `T` е нумерички тип (пр. `Integer`, `Double`, или било која класа која наследува од `java.lang.Number`) и враќа резултат`double` кој претставува стандардната девијација на вредностите во листата.
Стандардна девијација се пресметува со следната формула:
stem:[\sigma = \sqrt{\frac{1}{N} \sum_{i=1}^N (x_i - \mu)^2}, \mu = \frac{1}{N} \sum_{i=1}^N x_i]

.Решение (`MyMathClass.java`)
[source,java]
----
include::{source_dir}/MyMathClass.java[]
----

include::parts/footer.adoc[]

link:{sources_zip}/np_av6_src.zip[Source Code ZIP]