# Напредно програмирање
Аудиториски вежби 9
v1.0, 1 Декември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../examples/src/main/java/mk/ukim/finki/np/av9

== Колекции (Set, Map)

=== Birthdays paradox

Парадоксот на роденден е дека постои изненадувачки голема веројатност дека двајца луѓе во иста просторија имаат ист роденден.
Под ист роденден подразбираме дека се родени на ист ден во годината (ги игнорираме престпните).
Да се напише програма која апроксимативно ја пресметува веројатноста дека 2-ца или повеќе луѓе во иста просторија имаат ист роденден, за 2 до 50 луѓе во просторија.
Програмата треба да го пресмета одговорот со симулација.
Во повеќе обиди (пр. 5000), се доделува случаен роденден (пр. број од 1 - 365) на сите во просторијата.
Родендените се чуваат во `HashSet`.
Како што се генерираат случајни родендени, со помош на методот `contains` на `HashSet` се проверува дали тоj роденден е веќе назначен во собата.
Ако е тоа случај, се зголемува еден бројач коj брои колку пати барем 2-ца во собата имаат ист роденден и се преминува на следниот обид.
Излезот од вашата програма треба да биде во следниот облик.
Броевите нема да бидат сосема точни затоа што се употребуваат случајни броеви.

----
For 2 people, the probability of two birthdays is about 0.002
For 3 people, the probability of two birthdays is about 0.0082
For 4 people, the probability of two birthdays is about 0.0163
...
For 49 people, the probability of two birthdays is about 0.9654
For 50 people, the probability of two birthdays is about 0.969
----

.Решение (`Birthdays.java`)
[source,java]
----
include::{source_dir}/Birthdays.java[]
----

=== Names

Текстуалните датотеки `boynames.txt` и `girlnames.txt`, содржат листа од 1,000 од најпопуларните машки и женски имиња во САД за 2005 година.
Секој ред од датотеките се состои од име и број на регистрирани раѓања таа година со тоа име, со тоа што имињата се подредени по популарност.
Пример, датотеката `girlnames.txt` започнува со
----
Emily 25494
Emma 22532
----
Ова означува дека Emily е најпопуларно име со 25,494 регистрирани имиња.

Напишете програма која ќе најде колку имиња се наоѓаат и на двете листи, машката и женската.

.Решение (`Names.java`)
[source,java]
----
include::{source_dir}/Names.java[]
----

=== Audition

Да се имплементира класа за аудиција `Audition` со следните методи:

- `void addParticipant(String city, String code, String name, int age)` - додава нов кандидат со код `code`, име и возраст за аудиција во даден град `city`.
Во ист град не се дозволува додавање на кандидат со ист код како некој претходно додаден кандидат (додавањето се игнорира, а комплексноста на овој метод треба да биде `O(1)`)
- `void listByCity(String city)` - ги печати сите кандидати од даден град подредени според името, а ако е исто според возраста (комплексноста на овој метод не треба да надминува `O(n∗log2(n))`, каде `n` е бројот на кандидати во дадениот град).



include::parts/footer.adoc[]

link:{sources_zip}/np_av9_src.zip[Source Code ZIP]