# Напредно програмирање
Примери од втор парцијален испит
v1.0, 13 Декември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../exams/src/main/java/mk/ukim/finki/np/mt2

=== Најдобри филмови (2 парцијален испит 2014)

Да се имплементира класа `MoviesList` во која се чува листа од филмови (класа `Movie` за секој филм се дадени неговиот наслов и листа од рејтинзи (цели броеви од 1 до 10) и ги има следните методи:

- `public void addMovie(String title, int[] ratings)` - метод за додавање нов филм во листата (наслов и низа од рејтинзи)
- `public List<Movie> top10ByAvgRating()` - метод кој враќа листа од 10-те филмови со најдобар просечен рејтинг, подредени во опаѓачки редослед според рејтингот (ако два филмови имаат ист просечен рејтинг, се подредуваат лексикографски според името)
- `public List<Movie> top10ByRatingCoef()` - метод кој враќа листа од 10-те филмови со најдобар рејтинг коефициент (се пресметува како `просечен ретјтинг на филмот x вкупно број на рејтинзи на филмот / максимален број на рејтинзи (од сите филмови во листата)`

За класата `Movie` да се препокрие `toString()` методот да враќа соодветна репрезентација (погледнете го пример излезот).

[source,java]
----
include::{source_dir}/MoviesTest.java[]
----


=== Мерна станица (2 парцијален испит 2013)

Во една метеролошка станица на секои 5 минути пристигнуваат податоци за временските услови (температура, влажност на воздухот, ветар, видливост, време). Пример за вакви податоци:

- температура: 13 степени
- влажност: 98%
- ветар: 11.2 km/h
- видливост: 14 km
- време: 28.12.2013 14:37:55 (dd.MM.yyyy HH:mm:ss).

Потребно е да се имплементира класа `WeatherStation` која ќе ги чува податоците за временските услови за последните `x` денови (при додавање на податоци за ново мерење, сите мерења чие што време е постаро за `x` денови од новото се бришат).
Исто така ако времето на новото мерење кое се додава се разликува за помалку од 2.5 минути од времето на некое претходно додадено мерење, тоа треба да се игнорира (не се додава).

Да се имплементираат следните методи на класата `WeatherStation`:

- `WeatherStation(int days)` - конструктор со аргумент бројот на денови за кои се чуваат мерења
- `public void addMeasurement(float temperature, float wind, float humidity, float visibility, Date date)` - додавање на податоци за ново мерење
- `public int total()` - го враќа вкупниот број на мерења кои се чуваат
- `public void status(Date from, Date to)` - ги печати сите мерења во периодот од `from` до `to` подредени според датумот во растечки редослед и на крај ја печати просечната температура во овој период. Ако не постојат мерења во овој период се фрла исклучок од тип `RuntimeException` (вграден во Јава).

Пример за форматот на излезот:

----
24.6 80.2 km/h 28.7% 51.7 km Tue Dec 17 23:40:15 CET 2013
23.5 32.2 km/h 16.5% 187.2 km Tue Dec 17 23:45:15 CET 2013
13.2 67.1 km/h 18.9% 135.4 km Tue Dec 17 23:50:15 CET 2013
Avarage temperature: 20.43
----

[source,java]
----
include::{source_dir}/WeatherStationTest.java[]
----

=== Stadium (2 парцијален испит 2014)

Да се имплементира систем за билети за стадион.
За таа цел треба да се имплементираат класите:

 1. `Sector` во која се чуват информации за:
   - кодот на секторот `String`
   - бројот на места за седење `int`
   - информации за зафатеност на местата за седење `?`
 2. `Stadium` во која се чуваат информации за:
  - името на стадионот `String`
  - и сите сектори во стадионот `?`

Во класата `Stadium` треба да се имплементираат следните методи:

 - `Stadium(String name)` конструктор со аргумент име на стадионот
 - `void createSectors(String[] sectorNames, int[] sizes)` креирање на сектори со имиња `String[] sectorNames` и број на места `int[] sizes` (двете низи се со иста големина)
 - `void buyTicket(String sectorName, int seat, int type)` за купување билет од проследениот тип (`type`, 0 - неутрален, 1 - домашен, 2 - гостински), во секторот `sectorName` со број на место `seat` (местото секогаш е со вредност во опсег `1 - size`). Ако местото е зафатено (претходно е купен билет на ова место) се фрла исклучок од вид `SeatTakenException`. Исто така ако се обидеме да купиме билет од тип 1, во сектор во кој веќе има купено билет од тип 2 (и обратно) се фрла исклучок од вид `SeatNotAllowedException`.
 - `void showSectors()` ги печати сите сектори сортирани според бројот на слободни места во опаѓачки редослед (ако повеќе сектори имаат ист број на слободни места, се подредуваат според името).

[source,java]
----
include::{source_dir}/StadiumTest.java[]
----

include::parts/footer.adoc[]

link:{sources_zip}/np_exam_problems_2_src.zip[Source Code ZIP]