# Напредно програмирање
Примери од прв парцијален испит
v1.0, 20 Септември, 2016
include::parts/attributes.adoc[]

:source_dir: ../../exams/src/main/java/mk/ukim/finki/np/mt1

=== Time Table (1 парцијален испит 2014)

Да се имплементира класа `TimeTable` која ќе чита од влезен тек (стандарден влез, датотека, ...) податоци за времиња во 24-часовен формат.
Сите времиња се разделени со едно празно место, а во самото време часот и минутите може да бидат разделени со `:` или `.`.
Пример за форматот на податоците:

----
11:15 0.45 23:12 15:29 18.46
----

Ваша задача е да ги имплементирате методите:

* `TimeTable()` - default конструктор
* `void readTimes(InputStream inputStream)` - метод за читање на податоците
* `void writeTimes(OutputStream outputStream, TimeFormat format)` - метод кој ги печати сите времиња сортирани во растечки редослед во зададениот формат (24 часовен или AM/PM).

Методот за читање `readTimes` фрла исклучоци од тип `UnsupportedFormatException` ако времињата се разделени со нешто друго што не е `:` или `.` и `InvalidTimeException` ако времето (часот или минутите) е надвор од дозволениот опсег (0-23, 0-59).
И двата исклучоци во пораката `getMessage()` треба да го вратат влезниот податок кој го предизвикал исклучокот.
Сите времиња до моментот кога ќе се фрли некој од овие два исклучоци треба да си останат вчитани.
Правила за конверзија од 24-часовен формат во AM/PM:

. за првиот час од денот (0:00 - 0:59), додадете 12 и направете го "AM"
. од 1:00 до 11:59, само направето го "AM"
. од 12:00 до 12:59, само направето го "PM"
. од 13:00 до 23:59 одземете 12 и направете го "PM"

[source,java]
----
include::{source_dir}/TimesTest.java[]
----

=== MinMax (1 парцијален испит 2014)

Да се имплемнтира генеричка класа `MinMax` од два споредливи објекти (минимум/максимум).
За класата да се имплементираат:

* `MinMax()` - default конструктор
* `void update(T element)` - метод за ажурирање на тековните минимум/максимум
* `T max()` - го враќа најголемиот елемент
* `T min()` - го враќа најмалиот елемент
* да се преоптовари методот `toString()` кој враќа стринг составен од минималниот и максималниот елемент и бројот на елементи обработени во методот `update` кои се различни од тековниот минимум/максимум, разделени со празно место.

WARNING: Во класата не смеат да се чуваат елементите кои се обработуваат во методот `update`, освен тековниот минимум/максимум.

[source,java]
----
include::{source_dir}/MinAndMax.java[]
----

=== Stacked Canvas

Да се имплементира класа `Canvas` на која ќе чуваат различни форми.
За секоја форма се чува:

* `id:String`
* `color:Color` (enum дадена)

Притоа сите форми треба да имплментираат два интерфејси:

* `Scalable` - дефиниран со еден метод `void scale(float scaleFactor)` за соодветно зголемување/намалување на формата за дадениот фактор
* `Stackable` - дефиниран со еден метод `float weight()` кој враќа тежината на формата (се пресметува како плоштина на соодветната форма)

Во класата `Canvas` да се имплементираат следните методи:

* `void add(String id, Color color, float radius)` за додавање круг
* `void add(String id, Color color, float width, float height)` за додавање правоаголник

При додавањето на нова форма, во листата со форми таа треба да се смести на соодветното место според нејзината тежина. Елементите постојано се подредени според тежината во опаѓачки редослед.

* `void scale(String id, float scaleFactor)` - метод кој ја скалира формата со даденото id за соодветниот scaleFactor. Притоа ако има потреба, треба да се изврши преместување на соодветните форми, за да се задржи подреденоста на елементите.

*Не смее да се користи сортирање на листата.*

* `toString()` - враќа стринг составен од сите фигури во нов ред.
За секоја фигура се додава:
** `C: [id:5 места од лево] [color:10 места од десно] [weight:10.2 места од десно]` ако е круг
** `R: [id:5 места од лево] [color:10 места од десно] [weight:10.2 места од десно]` ако е правоаголник

*Користење на `instanceof` ќе се смета за неточно решение*

include::parts/footer.adoc[]

link:{sources_zip}/np_exam_problems_1_src.zip[Source Code ZIP]